devices:
  SW1:
    interfaces:
      - Ethernet0/0
      - Ethernet0/1
      - Ethernet0/2
      - Ethernet0/3
  SW2:
    interfaces:
      - Ethernet0/0
      - Ethernet0/1
      - Ethernet0/2
      - Ethernet0/3
  SW3:
    interfaces:
      - Ethernet0/0
      - Ethernet0/1
      - Ethernet0/2
      - Ethernet0/3

allowed_tasks:
  - vlan_create
  - vlan_access
  - stp_root
  - stp_priority
  - portfast
  - bpduguard